title: Keita Allen
author: GitHub User
email: kta [at] mit.edu
description: > # this means to ignore newlines until "baseurl:"
  just testing things out

# social links
github_username:  ktaallen # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
